/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author elkin
 */
public class ViewStory extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    Controller controller;
    boolean logged;
    
    public ViewStory() {
        controller = new Controller();
        logged = false;
        initComponents();
        jTPanel.setEnabledAt(2, logged);
        jPShare.setEnabled(false);
        jBLClose.setVisible(false);
        jLLName.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLogin = new javax.swing.JPanel();
        jTFLUser = new javax.swing.JTextField();
        jLLUser = new javax.swing.JLabel();
        jLLPass = new javax.swing.JLabel();
        jBLLogin = new javax.swing.JButton();
        jLLTitle = new javax.swing.JLabel();
        jLLName = new javax.swing.JLabel();
        jPFLPass = new javax.swing.JPasswordField();
        jBLClose = new javax.swing.JButton();
        jTPanel = new javax.swing.JTabbedPane();
        jPCreateUser = new javax.swing.JPanel();
        jLNameUser = new javax.swing.JLabel();
        jLLNuser = new javax.swing.JLabel();
        jLUser = new javax.swing.JLabel();
        jLPass = new javax.swing.JLabel();
        jTFNUser = new javax.swing.JTextField();
        jTFLNUser = new javax.swing.JTextField();
        jTFUser = new javax.swing.JTextField();
        jBCUser = new javax.swing.JButton();
        jBMUser = new javax.swing.JButton();
        jBDUser = new javax.swing.JButton();
        jPFPass = new javax.swing.JPasswordField();
        jPSearch = new javax.swing.JPanel();
        jLTitleFilter = new javax.swing.JLabel();
        jTFWord = new javax.swing.JTextField();
        jLWordSearch = new javax.swing.JLabel();
        jLTitleSearch = new javax.swing.JLabel();
        jLAuthorSearch = new javax.swing.JLabel();
        jCBAuthor = new javax.swing.JComboBox<>();
        jSPResult = new javax.swing.JScrollPane();
        jLResult = new javax.swing.JList<>();
        jBSearch = new javax.swing.JButton();
        jSPStory = new javax.swing.JScrollPane();
        jTAStory = new javax.swing.JTextArea();
        jSPDescription = new javax.swing.JScrollPane();
        jTADescription = new javax.swing.JTextArea();
        jCBType = new javax.swing.JComboBox<>();
        jLTypeSearch = new javax.swing.JLabel();
        jCBTitle = new javax.swing.JComboBox<>();
        jLBDescr = new javax.swing.JLabel();
        jLTitleSelected = new javax.swing.JLabel();
        jPShare = new javax.swing.JPanel();
        jLCSTitle = new javax.swing.JLabel();
        jSPCStory = new javax.swing.JScrollPane();
        jTPCStory = new javax.swing.JTextPane();
        jLCSAutor = new javax.swing.JLabel();
        jTFCTitle = new javax.swing.JTextField();
        jTFCAuthor = new javax.swing.JTextField();
        jLCSType = new javax.swing.JLabel();
        jCBCType = new javax.swing.JComboBox<>();
        jBCShare = new javax.swing.JButton();
        jBCChange = new javax.swing.JButton();
        jBCDelete = new javax.swing.JButton();
        jSPCStories = new javax.swing.JScrollPane();
        jLCStories = new javax.swing.JList<>();
        jLCSStories = new javax.swing.JLabel();
        jLCSDescription = new javax.swing.JLabel();
        jSPCDescription = new javax.swing.JScrollPane();
        jTACDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Historias");
        setResizable(false);

        jPLogin.setBackground(new java.awt.Color(255, 255, 255));

        jTFLUser.setMaximumSize(new java.awt.Dimension(140, 25));
        jTFLUser.setMinimumSize(new java.awt.Dimension(140, 25));
        jTFLUser.setPreferredSize(new java.awt.Dimension(140, 25));

        jLLUser.setText("User");

        jLLPass.setText("Password");

        jBLLogin.setToolTipText("");
        jBLLogin.setLabel("Log in");
        jBLLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLLoginActionPerformed(evt);
            }
        });

        jLLTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLLTitle.setText("Registro de historias");

        jLLName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLLName.setText("user");

        jPFLPass.setMaximumSize(new java.awt.Dimension(140, 25));
        jPFLPass.setMinimumSize(new java.awt.Dimension(140, 25));
        jPFLPass.setName(""); // NOI18N
        jPFLPass.setPreferredSize(new java.awt.Dimension(140, 25));

        jBLClose.setText("Cerrar sesion");
        jBLClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPLoginLayout = new javax.swing.GroupLayout(jPLogin);
        jPLogin.setLayout(jPLoginLayout);
        jPLoginLayout.setHorizontalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLoginLayout.createSequentialGroup()
                        .addComponent(jLLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLLUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLoginLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jBLClose))
                            .addGroup(jPLoginLayout.createSequentialGroup()
                                .addComponent(jLLName, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLLPass)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFLUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPFLPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPLoginLayout.setVerticalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFLUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLLUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLPass)
                    .addComponent(jPFLPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLClose)))
        );

        jLLPass.getAccessibleContext().setAccessibleName("");

        jTPanel.setToolTipText("");
        jTPanel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTPanel.setOpaque(true);
        jTPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPanelMouseClicked(evt);
            }
        });

        jLNameUser.setText("Nombre");

        jLLNuser.setText("Apellido");

        jLUser.setText("User");

        jLPass.setText("Password");

        jTFNUser.setMaximumSize(new java.awt.Dimension(140, 25));
        jTFNUser.setMinimumSize(new java.awt.Dimension(140, 25));
        jTFNUser.setPreferredSize(new java.awt.Dimension(200, 25));

        jTFLNUser.setMaximumSize(new java.awt.Dimension(140, 25));
        jTFLNUser.setMinimumSize(new java.awt.Dimension(140, 25));
        jTFLNUser.setPreferredSize(new java.awt.Dimension(200, 25));

        jTFUser.setMaximumSize(new java.awt.Dimension(140, 25));
        jTFUser.setMinimumSize(new java.awt.Dimension(140, 25));
        jTFUser.setPreferredSize(new java.awt.Dimension(200, 25));

        jBCUser.setText("Crear");
        jBCUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCUserActionPerformed(evt);
            }
        });

        jBMUser.setText("Modificar");
        jBMUser.setEnabled(false);
        jBMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMUserActionPerformed(evt);
            }
        });

        jBDUser.setText("Eliminar");
        jBDUser.setEnabled(false);
        jBDUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDUserActionPerformed(evt);
            }
        });

        jPFPass.setMaximumSize(new java.awt.Dimension(140, 25));
        jPFPass.setMinimumSize(new java.awt.Dimension(140, 25));
        jPFPass.setName(""); // NOI18N
        jPFPass.setPreferredSize(new java.awt.Dimension(140, 25));

        javax.swing.GroupLayout jPCreateUserLayout = new javax.swing.GroupLayout(jPCreateUser);
        jPCreateUser.setLayout(jPCreateUserLayout);
        jPCreateUserLayout.setHorizontalGroup(
            jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLNuser)
                    .addComponent(jLUser)
                    .addComponent(jLPass)
                    .addComponent(jLNameUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFUser, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jTFLNUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFNUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPFPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMUser, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jBDUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPCreateUserLayout.setVerticalGroup(
            jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNameUser)
                    .addComponent(jTFNUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMUser)
                    .addComponent(jTFLNUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLLNuser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDUser)
                    .addComponent(jTFUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPass)
                    .addComponent(jPFPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTPanel.addTab("Crear usuario", jPCreateUser);

        jLTitleFilter.setText("Escoge el filtro de busqueda");

        jTFWord.setToolTipText("Escibre aqui una palabra clave");
        jTFWord.setMaximumSize(new java.awt.Dimension(194, 30));
        jTFWord.setPreferredSize(new java.awt.Dimension(194, 28));

        jLWordSearch.setText("Palabra");

        jLTitleSearch.setText("Titulos");

        jLAuthorSearch.setText("Autores");

        jCBAuthor.setMaximumSize(new java.awt.Dimension(194, 24));
        jCBAuthor.setPreferredSize(new java.awt.Dimension(194, 24));

        jSPResult.setAutoscrolls(true);
        jSPResult.setOpaque(false);
        jSPResult.setPreferredSize(new java.awt.Dimension(259, 268));

        jLResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLResult.setToolTipText("Selecciona la historia que quieres leer");
        jLResult.setName(""); // NOI18N
        jLResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLResultMouseClicked(evt);
            }
        });
        jSPResult.setViewportView(jLResult);

        jBSearch.setText("Buscar");
        jBSearch.setMaximumSize(new java.awt.Dimension(262, 25));
        jBSearch.setPreferredSize(new java.awt.Dimension(262, 25));
        jBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSearchActionPerformed(evt);
            }
        });

        jTAStory.setEditable(false);
        jTAStory.setRows(5);
        jSPStory.setViewportView(jTAStory);

        jSPDescription.setMaximumSize(new java.awt.Dimension(297, 105));
        jSPDescription.setMinimumSize(new java.awt.Dimension(297, 105));
        jSPDescription.setPreferredSize(new java.awt.Dimension(297, 105));

        jTADescription.setEditable(false);
        jTADescription.setColumns(20);
        jTADescription.setRows(5);
        jTADescription.setMaximumSize(new java.awt.Dimension(287, 95));
        jTADescription.setMinimumSize(new java.awt.Dimension(287, 95));
        jTADescription.setPreferredSize(new java.awt.Dimension(287, 95));
        jSPDescription.setViewportView(jTADescription);

        jCBType.setMaximumSize(new java.awt.Dimension(194, 24));
        jCBType.setPreferredSize(new java.awt.Dimension(194, 24));

        jLTypeSearch.setText("Tipos");

        jCBTitle.setMaximumSize(new java.awt.Dimension(194, 24));
        jCBTitle.setPreferredSize(new java.awt.Dimension(194, 24));

        jLBDescr.setText("Descripcion Corta");

        jLTitleSelected.setText("Titulo:");

        javax.swing.GroupLayout jPSearchLayout = new javax.swing.GroupLayout(jPSearch);
        jPSearch.setLayout(jPSearchLayout);
        jPSearchLayout.setHorizontalGroup(
            jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTitleFilter)
                    .addComponent(jSPResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSearchLayout.createSequentialGroup()
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLAuthorSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLTitleSearch))
                                .addComponent(jLTypeSearch))
                            .addComponent(jLWordSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBAuthor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPStory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPSearchLayout.createSequentialGroup()
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitleSelected)
                            .addComponent(jLBDescr))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSPDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPSearchLayout.setVerticalGroup(
            jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTitleFilter)
                    .addComponent(jLBDescr))
                .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSearchLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLWordSearch)
                            .addComponent(jTFWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTypeSearch)
                            .addComponent(jCBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTitleSearch)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSearchLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPSearchLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLTitleSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPStory, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPSearchLayout.createSequentialGroup()
                        .addGroup(jPSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPSearchLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jCBAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPSearchLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLAuthorSearch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPanel.addTab("Buscar Historias", jPSearch);

        jPShare.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLCSTitle.setText("Titulo:");

        jTPCStory.setMaximumSize(new java.awt.Dimension(350, 340));
        jTPCStory.setSelectionEnd(10);
        jSPCStory.setViewportView(jTPCStory);

        jLCSAutor.setText("Autor:");

        jLCSType.setText("Tipo");

        jBCShare.setText("Compartir");
        jBCShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCShareActionPerformed(evt);
            }
        });

        jBCChange.setText("Modificar");
        jBCChange.setEnabled(false);
        jBCChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCChangeActionPerformed(evt);
            }
        });

        jBCDelete.setText("Eliminar");
        jBCDelete.setEnabled(false);
        jBCDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCDeleteActionPerformed(evt);
            }
        });

        jLCStories.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLCStories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCStoriesMouseClicked(evt);
            }
        });
        jSPCStories.setViewportView(jLCStories);

        jLCSStories.setText("Tus Historias");

        jLCSDescription.setText("Descripcion corta");

        jTACDescription.setColumns(20);
        jTACDescription.setRows(5);
        jSPCDescription.setViewportView(jTACDescription);

        javax.swing.GroupLayout jPShareLayout = new javax.swing.GroupLayout(jPShare);
        jPShare.setLayout(jPShareLayout);
        jPShareLayout.setHorizontalGroup(
            jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPShareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPShareLayout.createSequentialGroup()
                        .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPShareLayout.createSequentialGroup()
                                .addComponent(jBCShare, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLCSTitle))
                            .addGroup(jPShareLayout.createSequentialGroup()
                                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBCDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBCChange, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCSAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLCSType, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(22, 22, 22))
                    .addGroup(jPShareLayout.createSequentialGroup()
                        .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCSDescription)
                            .addComponent(jSPCStories, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCSStories)
                            .addComponent(jSPCDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFCAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBCType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 350, Short.MAX_VALUE)
                    .addComponent(jTFCTitle)
                    .addComponent(jSPCStory))
                .addContainerGap())
        );
        jPShareLayout.setVerticalGroup(
            jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPShareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCSTitle)
                    .addComponent(jTFCTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCShare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCChange)
                    .addComponent(jLCSAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBCType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCDelete)
                        .addComponent(jLCSType)))
                .addGap(18, 18, 18)
                .addGroup(jPShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPCStory)
                    .addGroup(jPShareLayout.createSequentialGroup()
                        .addComponent(jLCSDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPCDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLCSStories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPCStories, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTPanel.addTab("Compartir Historias", jPShare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        jTPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLLoginActionPerformed
        if(controller.getByUserName(jTFLUser.getText())){
            if(controller.validatePassword(jPFLPass.getPassword())){
                logged = true;
                changeToLoginView();
                setUserDataFields();
                JOptionPane.showMessageDialog(this,"Has iniciado sesion correctamente");
            }
            else{
                JOptionPane.showMessageDialog(this,"Contraseña incorrecta");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"No existe el usuario :"+ jTFLUser.getText());
        }
    }//GEN-LAST:event_jBLLoginActionPerformed

    private void jBCUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCUserActionPerformed
        if(controller.validateEmptyField(jTFNUser.getText(),jTFLNUser.getText(),jTFUser.getText(),jPFPass.getPassword())){
            if(!controller.getByUserName(jTFUser.getText())){
                if(controller.createUser()){
                    logged = true;
                    changeToLoginView();
                    setUserDataFields();
                }else{
                   JOptionPane.showMessageDialog(this,"No se creo el usuario");
                }
            }else{
                JOptionPane.showMessageDialog(this,"Este nombre de usuario "+ jTFUser.getText()+" ya existe");
                jTFUser.setText("");
            }   
       
        }else{
            JOptionPane.showMessageDialog(this,"Información incorrecta");
        }
    }//GEN-LAST:event_jBCUserActionPerformed

    private void jBLCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLCloseActionPerformed
        logged = false;
        changeToFirstView();
        
    }//GEN-LAST:event_jBLCloseActionPerformed

    private void jBMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMUserActionPerformed
        if(controller.validateEmptyField(jTFNUser.getText(),jTFLNUser.getText(),jTFUser.getText(),jPFPass.getPassword())){
            if(controller.updateUser()){
                changeToLoginView();
                setUserDataFields();
                JOptionPane.showMessageDialog(this,"Los cambios se hicieron correctamente");
            }
        }
    }//GEN-LAST:event_jBMUserActionPerformed

    private void jBDUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDUserActionPerformed
        int option = JOptionPane.showConfirmDialog(this,"¿Estás seguro de eliminar tu cuenta?\nPerderas todas tus historias","Eliminar cuenta",JOptionPane.OK_CANCEL_OPTION);
        if (option==JOptionPane.OK_OPTION){
            if(controller.deleteUser()){
                JOptionPane.showMessageDialog(this,"Cuenta Eliminada");
                logged = false;
                changeToFirstView();
            }
        }
    }//GEN-LAST:event_jBDUserActionPerformed

    private void jTPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPanelMouseClicked
        clearFieldsSearchPanel();
        if(jTPanel.getSelectedIndex()==1){
            jCBType.removeAllItems();
            jCBTitle.removeAllItems();
            jCBAuthor.removeAllItems();
            jCBType.addItem("");
            jCBTitle.addItem("");
            jCBAuthor.addItem("");
            if (controller.loadStoryTypes()){
                for(String story : controller.getStoryTypes()){
                    jCBType.addItem(story);
                }
            } 
            if (controller.loadStoryAutor()){
                for (String author: controller.getStoryAutor()){
                    jCBAuthor.addItem(author);
                }
            }
            if (controller.loadStoryTitle()){
                for (String title: controller.getStoryTitle()){
                    jCBTitle.addItem(title);
                }
            }
        }
        if(jTPanel.getSelectedIndex()==2){
            jCBCType.removeAllItems();
            jCBCType.addItem("");
            if (logged){
                if (controller.loadStoryTypes()){
                    for(String type : controller.getStoryTypes()){
                        jCBCType.addItem(type);
                    }
                }
                if (controller.createQueryStory("",0,"","",controller.getId())){
                    if(controller.getStories().isEmpty()){
                        jLCStories.setVisible(false);
                    }
                    else{
                        jLCStories.setVisible(true);
                    }
                    jLCSStories.setEnabled(true);
                    DefaultListModel model = new DefaultListModel();
                    for (int i = 0; i < controller.getStories().size();i++){
                        model.addElement(controller.getStories().get(i).getTitle());
                    }
                    jLCStories.setModel(model);
                }
                
                
            }
        }
    }//GEN-LAST:event_jTPanelMouseClicked

    private void jLCStoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCStoriesMouseClicked
        jBCShare.setEnabled(false);
        jTFCTitle.setText(controller.getStories().get(jLCStories.getSelectedIndex()).getTitle());
        jTFCAuthor.setText(controller.getStories().get(jLCStories.getSelectedIndex()).getAutor());
        jTACDescription.setText(controller.getStories().get(jLCStories.getSelectedIndex()).getShortDescription());
        jTPCStory.setText(controller.getStories().get(jLCStories.getSelectedIndex()).getStory());
        jCBCType.setSelectedIndex(controller.getStories().get(jLCStories.getSelectedIndex()).getStoryTypeId());
        controller.setIdStory(controller.getStories().get(jLCStories.getSelectedIndex()).getId());
        jBCChange.setEnabled(true);
        jBCDelete.setEnabled(true);
    }//GEN-LAST:event_jLCStoriesMouseClicked

    private void jBCDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCDeleteActionPerformed
        int option = JOptionPane.showConfirmDialog(this,"¿Estás seguro de eliminar esta historia?","Eliminar historia",JOptionPane.OK_CANCEL_OPTION);
        if (option==JOptionPane.OK_OPTION){
            if(controller.deleteUserStory()){
                jCBCType.removeAllItems();
                jCBCType.addItem("");
                jBCShare.setEnabled(true);
                jBCChange.setEnabled(false);
                jBCDelete.setEnabled(false);
                jTFCTitle.setText("");
                jTFCAuthor.setText("");
                jTACDescription.setText("");
                jTPCStory.setText("");
                
                if (controller.loadStoryTypes()){
                    for(String type : controller.getStoryTypes()){
                        jCBCType.addItem(type);
                    }
                }
                if (controller.createQueryStory("",0,"","",controller.getUserId())){
                    DefaultListModel model = new DefaultListModel();
                    for (int i = 0; i < controller.getStories().size();i++){
                        model.addElement(controller.getStories().get(i).getTitle());
                    }
                    jLCStories.setModel(model);
                }

                JOptionPane.showMessageDialog(this,"Historia Eliminada");

            }
        }
    }//GEN-LAST:event_jBCDeleteActionPerformed

    private void jBCChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCChangeActionPerformed
        if(controller.validateEmptyField(jTFCTitle.getText(),jTFCAuthor.getText(),jCBCType.getSelectedIndex(), jTPCStory.getText(),jTACDescription.getText())){
            if(controller.updateUserStory()){
                jBCShare.setEnabled(true);
                jBCChange.setEnabled(false);
                jBCDelete.setEnabled(false);
                jTFCTitle.setText("");
                jTFCAuthor.setText("");
                jTACDescription.setText("");
                jTPCStory.setText("");
                jCBCType.removeAllItems();
                jCBCType.addItem("");
                if (controller.loadStoryTypes()){
                    for(String type : controller.getStoryTypes()){
                        jCBCType.addItem(type);
                    }
                }
                if (controller.createQueryStory("",0,"","",controller.getUserId())){
                    DefaultListModel model = new DefaultListModel();
                    for (int i = 0; i < controller.getStories().size();i++){
                        model.addElement(controller.getStories().get(i).getTitle());
                    }
                    jLCStories.setModel(model);
                }
                JOptionPane.showMessageDialog(this,"Los cambios se hicieron correctamente");
            }
        }
    }//GEN-LAST:event_jBCChangeActionPerformed

    private void jBCShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCShareActionPerformed
        if(controller.validateEmptyField(jTFCTitle.getText(),jTFCAuthor.getText(),jCBCType.getSelectedIndex(), jTPCStory.getText(),jTACDescription.getText())){
            controller.setUserId(controller.getUserId());
            if(controller.createUserStory()){
                jTFCTitle.setText("");
                jTFCAuthor.setText("");
                jTACDescription.setText("");
                jTPCStory.setText("");
                jCBCType.removeAllItems();
                jCBCType.addItem("");
                jTFCAuthor.setText(controller.getName()+" "+controller.getLastName());
            if (logged){
                if (controller.loadStoryTypes()){
                    for(String type : controller.getStoryTypes()){
                        jCBCType.addItem(type);
                    }
                }
                if (controller.createQueryStory("",0,"","",controller.getId())){
                    if(controller.getStories().isEmpty()){
                        jLCStories.setVisible(false);
                    }
                    else{
                        jLCStories.setVisible(true);
                    }
                    jLCSStories.setEnabled(true);
                    DefaultListModel model = new DefaultListModel();
                    for (int i = 0; i < controller.getStories().size();i++){
                        model.addElement(controller.getStories().get(i).getTitle());
                    }
                    jLCStories.setModel(model);
                }
                
                
            }
                JOptionPane.showMessageDialog(this,"Se compartio tu historia con exito");
            }else{
                JOptionPane.showMessageDialog(this,"No pude compartir tu historia");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Debes llenar todos los campos");
        }
    }//GEN-LAST:event_jBCShareActionPerformed

    private void jBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSearchActionPerformed
        if (controller.createQueryStory(jTFWord.getText(),jCBType.getSelectedIndex(),jCBTitle.getSelectedItem().toString(),jCBAuthor.getSelectedItem().toString(),null)){
            DefaultListModel model = new DefaultListModel();
            if(controller.getStories().size()==0){
                jLResult.setVisible(false);
            }
            else{
                jLResult.setVisible(true);
            }
            for (int i = 0; i < controller.getStories().size();i++){
                model.addElement("Titulo: "+controller.getStories().get(i).getTitle()+" - Autor: "+controller.getStories().get(i).getAutor());
            }
            jLResult.setModel(model);
            
        }
    }//GEN-LAST:event_jBSearchActionPerformed

    private void jLResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLResultMouseClicked
        jLTitleSelected.setText(controller.getStories().get(jLResult.getSelectedIndex()).getTitle());
        jTADescription.setText(controller.getStories().get(jLResult.getSelectedIndex()).getShortDescription());
        jTAStory.setText(controller.getStories().get(jLResult.getSelectedIndex()).getStory());
    }//GEN-LAST:event_jLResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCChange;
    private javax.swing.JButton jBCDelete;
    private javax.swing.JButton jBCShare;
    private javax.swing.JButton jBCUser;
    private javax.swing.JButton jBDUser;
    private javax.swing.JButton jBLClose;
    private javax.swing.JButton jBLLogin;
    private javax.swing.JButton jBMUser;
    private javax.swing.JButton jBSearch;
    private javax.swing.JComboBox<String> jCBAuthor;
    private javax.swing.JComboBox<String> jCBCType;
    private javax.swing.JComboBox<String> jCBTitle;
    private javax.swing.JComboBox<String> jCBType;
    private javax.swing.JLabel jLAuthorSearch;
    private javax.swing.JLabel jLBDescr;
    private javax.swing.JLabel jLCSAutor;
    private javax.swing.JLabel jLCSDescription;
    private javax.swing.JLabel jLCSStories;
    private javax.swing.JLabel jLCSTitle;
    private javax.swing.JLabel jLCSType;
    private javax.swing.JList<String> jLCStories;
    private javax.swing.JLabel jLLName;
    private javax.swing.JLabel jLLNuser;
    private javax.swing.JLabel jLLPass;
    private javax.swing.JLabel jLLTitle;
    private javax.swing.JLabel jLLUser;
    private javax.swing.JLabel jLNameUser;
    private javax.swing.JLabel jLPass;
    private javax.swing.JList<String> jLResult;
    private javax.swing.JLabel jLTitleFilter;
    private javax.swing.JLabel jLTitleSearch;
    private javax.swing.JLabel jLTitleSelected;
    private javax.swing.JLabel jLTypeSearch;
    private javax.swing.JLabel jLUser;
    private javax.swing.JLabel jLWordSearch;
    private javax.swing.JPanel jPCreateUser;
    private javax.swing.JPasswordField jPFLPass;
    private javax.swing.JPasswordField jPFPass;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPanel jPSearch;
    private javax.swing.JPanel jPShare;
    private javax.swing.JScrollPane jSPCDescription;
    private javax.swing.JScrollPane jSPCStories;
    private javax.swing.JScrollPane jSPCStory;
    private javax.swing.JScrollPane jSPDescription;
    private javax.swing.JScrollPane jSPResult;
    private javax.swing.JScrollPane jSPStory;
    private javax.swing.JTextArea jTACDescription;
    private javax.swing.JTextArea jTADescription;
    private javax.swing.JTextArea jTAStory;
    private javax.swing.JTextField jTFCAuthor;
    private javax.swing.JTextField jTFCTitle;
    private javax.swing.JTextField jTFLNUser;
    private javax.swing.JTextField jTFLUser;
    private javax.swing.JTextField jTFNUser;
    private javax.swing.JTextField jTFUser;
    private javax.swing.JTextField jTFWord;
    private javax.swing.JTextPane jTPCStory;
    private javax.swing.JTabbedPane jTPanel;
    // End of variables declaration//GEN-END:variables

    public void setController(Controller controller) {
        this.controller = controller;
    }

    private void changeToLoginView() {
        jBCUser.setEnabled(false);
        jBMUser.setEnabled(true);
        jBDUser.setEnabled(true);
        jLLUser.setVisible(false);
        jLLPass.setVisible(false);
        jBLLogin.setVisible(false);
        jBLClose.setVisible(true);
        jTFUser.setEditable(false);
        jTFLUser.setVisible(false);
        jPFLPass.setVisible(false);
        jLLName.setText("Autor: "+controller.getName()+" "+controller.getLastName());
        jLLName.setVisible(true);
        jPLogin.setBackground(new Color(187,206,163));
        jPCreateUser.setBackground(new Color(240,254,151));
        jPSearch.setBackground(new Color(240,254,151));
        jPShare.setBackground(new Color(240,254,151));
        jTFCAuthor.setText(controller.getName()+" "+controller.getLastName());
        jTPanel.setEnabledAt(2, logged);
        
    }

    private void setUserDataFields() {
        jTPanel.setTitleAt(0, "Perfil de usuario");
        jTFNUser.setText(controller.getName());
        jTFLNUser.setText(controller.getLastName());
        jTFUser.setText(controller.getUserName());
        jPFPass.setText(controller.getPass());
    }

    private void changeToFirstView() {
        jBCUser.setEnabled(true);
        jBMUser.setEnabled(false);
        jBDUser.setEnabled(false);
        jLLUser.setVisible(true);
        jLLPass.setVisible(true);
        jBLLogin.setVisible(true);
        jBLClose.setVisible(false);
        jTFUser.setEditable(true);
        jTFLUser.setVisible(true);
        jPFLPass.setVisible(true);
        jLLName.setText("");
        jLLName.setVisible(false);
        jTPanel.setTitleAt(0, "Crear usuario");
        jTFNUser.setText("");
        jTFLNUser.setText("");
        jTFUser.setText("");
        jPFPass.setText("");
        jTFLUser.setText("");
        jPFLPass.setText("");
        jPLogin.setBackground(new Color(255,255,255));
        jPCreateUser.setBackground(new Color(238,238,238));
        jPSearch.setBackground(new Color(238,238,238));
        jPShare.setBackground(new Color(238,238,238));
        jTPanel.setEnabledAt(2, logged);
        jTPanel.setSelectedIndex(0);
        jTFCAuthor.setText("");
        jTFCTitle.setText("");
        jTPCStory.setText("");
        jBCShare.setEnabled(true);
        jBCChange.setEnabled(false);
        jBCDelete.setEnabled(false);
        jTFCAuthor.removeAll();
        jTACDescription.setText("");
    }

    private void clearFieldsSearchPanel() {
        jTFWord.setText("");
        jTADescription.setText("");
        jTAStory.setText("");
        jLTitleSelected.setText("Titulo");
        jCBType.removeAllItems();
            jCBTitle.removeAllItems();
            jCBAuthor.removeAllItems();
            jCBType.addItem("");
            jCBTitle.addItem("");
            jCBAuthor.addItem("");
            if (controller.loadStoryTypes()){
                for(String story : controller.getStoryTypes()){
                    jCBType.addItem(story);
                }
            } 
            if (controller.loadStoryAutor()){
                for (String author: controller.getStoryAutor()){
                    jCBAuthor.addItem(author);
                }
            }
            if (controller.loadStoryTitle()){
                for (String title: controller.getStoryTitle()){
                    jCBTitle.addItem(title);
                }
            }
        DefaultListModel model = new DefaultListModel();
        jLResult.setModel(model);
        jLResult.setVisible(false);
        
        
    }

 
}

